#!/usr/bin/env python3

"""
The Cryptopals Crypto Challenges For Python

Usage:
  tcccfp all [--no-banner]
  tcccfp set <set_number> [--no-banner]
  tcccfp chall <chall_number> [--no-banner]
  tcccfp -h | --version

Commands:
  all         Tests every challenge.
  set         Tests every challenge of a set.
  chall       Tests a single challenge.

Options:
  -h --help     Show this screen.
  --version     Show version.
  --no-banner   Does not displays the beautiful banner

"""

from docopt import docopt
import test_suite
import sys
import os

cur_dir = os.getcwd()
if cur_dir not in sys.path:
    sys.path.append(cur_dir)


def print_banner():
    with open("banner.txt", 'r') as f:
        print(f.read())
        print('\n\n')


if __name__ == "__main__":
    tccfp_args = docopt(__doc__)

    if not tccfp_args['--no-banner']:
        print_banner()

    print(tccfp_args)

    if tccfp_args['all']:
        print("Running Set 1")
        for i in range(1, 65):
            set_number = ((i-1)//8)+1

            if i % 8 == 0:
                print("Running Set {}".format(set_number))

            print("Running Challenge {}".format(i))
            test_suite.run_tests_on("challenges.set{}.c{}.solve".format(set_number, i))
    
    if tccfp_args['chall']:
        chall_number = int(tccfp_args['<chall_number>'])
        set_number = ((chall_number-1)//8)+1
        chall_path = "challenges.set{}.c{}.solve".format(set_number, chall_number)
        test_suite.run_tests_on(chall_path)

