import test_suite
from aux.rng.mt32 import MT as rand
from time import time
import pprint


class Testing(test_suite.TestCase):

    def test_challenge1(self):

        seed = int(time())
        mt = rand()
        mt.seed(seed)
        
        #first we need to get the numbers generated by all the states
        #the 32 bits of mersene have 634 ints of internal state

        numbers = [mt.get_number() for _ in range(634)]

        self.assertEqual(0,1)
        
all = Testing